// code/renderers/vue3/template/components/Html.vue
<template>
  <div v-html="contentValue"></div>
</template>

<script>
export default {
  name: 'my-html',

  props: {
    content: {
      type: [String, Function],
      required: true,
    },
  },

  computed: {
    contentValue() {
      return typeof this.content === 'function' ? this.content() : this.content;
    },
  },

  setup() {},
};
</script>

// code/renderers/react/template/components/Html.jsx
import React from 'react';

import PropTypes from 'prop-types';

export const Html = ({ content }) => {
  const contentValue = typeof content === 'function' ? content() : content;
  return <div dangerouslySetInnerHTML={{ __html: contentValue }} />;
};

Html.propTypes = {
  content: PropTypes.oneOfType([PropTypes.string, PropTypes.func]).isRequired,
};
